"""
Flow B: Automatically triggered by Flow A's event.

This flow is triggered automatically when Flow A emits the
'italy.random.number.generated' event. It receives the event data
and logs information visible in Prefect Cloud UI.
"""

from prefect import flow, task


@task
def process_event_data(random_number) -> dict:
    """
    Process the event data received from Flow A.
    
    Args:
        random_number: The random number generated by Flow A
        
    Returns:
        A dictionary with processed information
    """
    result = {
        "received_number": random_number,
        "message": f"Flow B received random number: {random_number}",
        "status": "success",
    }
    return result


@flow(name="flow-b", log_prints=True)
def flow_b(random_number=10):  # random_number is passed automatically by Prefect automation       # type: ignore  # noqa: E501        
    """
    Flow B: Triggered automatically by Flow A's event.
    
    This flow:
    1. Receives the random number from Flow A's event
    2. Processes the event data
    3. Logs information visible in Prefect Cloud UI
    
    Args:
        random_number: The random number from Flow A's event payload
                       (passed automatically by Prefect automation)
    """
    print("=" * 50)
    print("Flow B started: Processing event from Flow A")
    print("=" * 50)
    
    if random_number is None:
        print("⚠️  Warning: No random number received in event payload")
        print("Flow B completed (no data to process)")
        return None
    
    print(f"✅ Received event 'italy.random.number.generated'")
    print(f"📊 Random number from Flow A: {random_number}")
    
    # Process the event data
    result = process_event_data(random_number)
    
    print(f"✅ Event data processed successfully")
    print(f"📝 Result: {result['message']}")
    print(f"🎯 Status: {result['status']}")
    print("=" * 50)
    print("Flow B completed successfully!")
    print("=" * 50)
    
    return result


if __name__ == "__main__":
    # Allow running locally for testing
    # Pass a test number to simulate the event
    flow_b(random_number=42)

